<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'ecbae1b93e1b084e878cf9d829e0d3fa',
  'MAILER_URL' => 'null://localhost',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/laboutiquefrançaise?serverVersion=mariadb-10.4.8&charset=utf8',
);
